### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by baliomega** [dsingleton/now-playing-radiator#4]
Hi,

Is there anyway to display the 'now playing' without prompting for username?

Thanks.

**Comment by todrobbins** [comment]
@baliomega,

Change the contents of the <script> tag in index.html to this: 

```
(function (document) {
    
    // var get_username = function() {
    //     // format: #username, or #!/user/username, prompt fallback
    //     return document.location.hash.split('/')[2] || 
    //                    document.location.hash.substring(1) || 
    //                    prompt('Enter a Last.fm username?');
    // };

    $(document).ready(function() {        
        // Canonicalise/Persist hash
        document.location.hash = username = '[your last.fm username]'
    
        var api = new LastfmAPI('5f134f063744307ee6f126ac2c480fab');

        np = new NowPlaying(api, username);
        np.autoUpdate();
    });

    // Needs replacing with a cross browser jquery plugin
    // window.onhashchange = function(event) {
    //     username = get_username();
    //     if (username != np.user) {
    //         np.user = username;
    //         np.update();
    //     }
    // };
    
})(document);
```

Just set `username = '[your last.fm username]'` and on load it'll populate the URL hash and begin pinging the API.

**Comment by dsingleton** [comment]
Hi @baliomega,

I must have missed the initial issue, sorry!

Once you've entered your username the URL is updated to include, so if you share the link with someone, or bookmark it, they'll be be shown your now playing - without prompting for a username.

Or you can edit the URL directly to set a user, for example, my Last.fm username is `underpangs`, so if I visit  `http://dsingleton.github.io/now-playing-radiator/#underpangs` i'l get my now playing without a prompt.

**Comment by baliomega** [comment]
Hi @dsingleton & @todrobbins ,

Thanks for your reply. It's working now. Thanks again!
